#!/usr/bin/perl
# This script requires libintl-perl(>=1.09).
use Locale::TextDomain ("maintaining.texi" => "./po/gettext/doc/emacs");
my ($en, $ja);
while (<>) {
	($en, $ja) = (quotemeta('@chapter Maintaining Large Programs'), __ '@chapter Maintaining Large Programs'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Change Logs'), __ '@section Change Logs'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Emacs Development Environment'), __ '@section Emacs Development Environment'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Find Identifier References'), __ '@section Find Identifier References'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Version Control'), __ '@section Version Control'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Working with Projects'), __ '@section Working with Projects'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Basic Editing under Version Control'), __ '@subsection Basic Editing under Version Control'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Change Log Commands'), __ '@subsection Change Log Commands'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Examining And Comparing Old Revisions'), __ '@subsection Examining And Comparing Old Revisions'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Features of the Log Entry Buffer'), __ '@subsection Features of the Log Entry Buffer'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Find Identifiers'), __ '@subsection Find Identifiers'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Format of ChangeLog'), __ '@subsection Format of ChangeLog'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Ignore Version Control Files'), __ '@subsection Ignore Version Control Files'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Introduction to Version Control'), __ '@subsection Introduction to Version Control'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Registering a File for Version Control'), __ '@subsection Registering a File for Version Control'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Selecting a Tags Table'), __ '@subsection Selecting a Tags Table'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Tags Tables'), __ '@subsection Tags Tables'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Undoing Version Control Actions'), __ '@subsection Undoing Version Control Actions'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection VC Change Log'), __ '@subsection VC Change Log'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection VC Directory Mode'), __ '@subsection VC Directory Mode'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Version Control Branches'), __ '@subsection Version Control Branches'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Version Control and the Mode Line'), __ '@subsection Version Control and the Mode Line'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Advanced Control in @kbd{C-x v v}'), __ '@subsubsection Advanced Control in @kbd{C-x v v}'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Basic Version Control with Locking'), __ '@subsubsection Basic Version Control with Locking'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Basic Version Control with Merging'), __ '@subsubsection Basic Version Control with Merging'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Changeset-based vs File-based Version Control'), __ '@subsubsection Changeset-based vs File-based Version Control'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Commands Available in the @file{*xref*} Buffer'), __ '@subsubsection Commands Available in the @file{*xref*} Buffer'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Concepts of Version Control'), __ '@subsubsection Concepts of Version Control'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Creating New Branches'), __ '@subsubsection Creating New Branches'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Creating Tags Tables'), __ '@subsubsection Creating Tags Tables'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Decentralized vs Centralized Repositories'), __ '@subsubsection Decentralized vs Centralized Repositories'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Etags Regexps'), __ '@subsubsection Etags Regexps'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Identifier Inquiries'), __ '@subsubsection Identifier Inquiries'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Looking Up Identifiers'), __ '@subsubsection Looking Up Identifiers'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Merge-based vs Lock-based Version Control'), __ '@subsubsection Merge-based vs Lock-based Version Control'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Merging Branches'), __ '@subsubsection Merging Branches'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Pulling/Pushing Changes into/from a Branch'), __ '@subsubsection Pulling/Pushing Changes into/from a Branch'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Searching and Replacing with Identifiers'), __ '@subsubsection Searching and Replacing with Identifiers'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Source File Tag Syntax'), __ '@subsubsection Source File Tag Syntax'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Supported Version Control Systems'), __ '@subsubsection Supported Version Control Systems'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Switching between Branches'), __ '@subsubsection Switching between Branches'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection The VC Directory Buffer'), __ '@subsubsection The VC Directory Buffer'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Types of Log File'), __ '@subsubsection Types of Log File'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection Understanding the Problems it Addresses'), __ '@subsubsection Understanding the Problems it Addresses'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsubsection VC Directory Commands'), __ '@subsubsection VC Directory Commands'); s/$en/$ja/;
	print;
}