#!/usr/bin/perl
# This script requires libintl-perl(>=1.09).
use Locale::TextDomain ("/data/data/com.termux/files/home/gitroot/emacs-doc-I18N/doc/misc/vip.texi" => "/data/data/com.termux/files/home/gitroot/emacs-doc-I18N/po/gettext/doc/misc");
my ($en, $ja);
while (<>) {
	($en, $ja) = (quotemeta('@chapter A Survey of VIP'), __ '@chapter A Survey of VIP'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Basic Concepts'), __ '@section Basic Concepts'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Loading VIP'), __ '@section Loading VIP'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Modes in VIP'), __ '@section Modes in VIP'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Emacs Mode'), __ '@subsection Emacs Mode'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Vi Mode'), __ '@subsection Vi Mode'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Insert Mode'), __ '@subsection Insert Mode'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Differences from Vi'), __ '@section Differences from Vi'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Undoing'), __ '@subsection Undoing'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Changing'), __ '@subsection Changing'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Searching'), __ '@subsection Searching'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection z Command'), __ '@subsection z Command'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Counts'), __ '@subsection Counts'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Marking'), __ '@subsection Marking'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Region Commands'), __ '@subsection Region Commands'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Some New Commands'), __ '@subsection Some New Commands'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection New Key Bindings'), __ '@subsection New Key Bindings'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Window Commands'), __ '@subsection Window Commands'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Buffer Commands'), __ '@subsection Buffer Commands'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection File Commands'), __ '@subsection File Commands'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Miscellaneous Commands'), __ '@subsection Miscellaneous Commands'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@chapter Vi Commands'), __ '@chapter Vi Commands'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Numeric Arguments'), __ '@section Numeric Arguments'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Important Keys'), __ '@section Important Keys'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Buffers and Windows'), __ '@section Buffers and Windows'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Files'), __ '@section Files'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Viewing the Buffer'), __ '@section Viewing the Buffer'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Mark Commands'), __ '@section Mark Commands'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Motion Commands'), __ '@section Motion Commands'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Searching and Replacing'), __ '@section Searching and Replacing'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Modifying Commands'), __ '@section Modifying Commands'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Delete Commands'), __ '@subsection Delete Commands'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Yank Commands'), __ '@subsection Yank Commands'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Put Back Commands'), __ '@subsection Put Back Commands'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Change Commands'), __ '@subsection Change Commands'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@subsection Repeating and Undoing Modifications'), __ '@subsection Repeating and Undoing Modifications'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Other Vi Commands'), __ '@section Other Vi Commands'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Insert Mode'), __ '@section Insert Mode'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@chapter Ex Commands'), __ '@chapter Ex Commands'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Ex Command Reference'), __ '@section Ex Command Reference'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@chapter Customization'), __ '@chapter Customization'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Customizing Constants'), __ '@section Customizing Constants'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@section Customizing Key Bindings'), __ '@section Customizing Key Bindings'); s/$en/$ja/;
	($en, $ja) = (quotemeta('@appendix GNU Free Documentation License'), __ '@appendix GNU Free Documentation License'); s/$en/$ja/;
	print;
}